#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: Robot_1/pose
        pose2d: Robot_1/ground_pose
        child_frame_id: Robot_1/base_link
        parent_frame_id: world
        use_new_coordinates: false
    '2':
        pose: Robot_2/pose
        pose2d: Robot_2/ground_pose
        child_frame_id: Robot_4/base_link
        parent_frame_id: world
        use_new_coordinates: false
    '3':
        pose: Robot_3/pose
        pose2d: Robot_3/ground_pose
        child_frame_id: Robot_3/base_link
        parent_frame_id: world
        use_new_coordinates: false
optitrack_config:
        multicast_address: 239.255.42.99
